### PR TITLE
FEATURE: MSF-20051 Fix Sonar

### PR DESCRIPTION
**Pull request by duynk3**

### CODE REVIEW

**Comment by duynk3** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by duynk3** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Review by anvuong119 — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/ait-merge-compliance-check/3/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/ait-fossa-scanning-oss-zuul-el7/3/ : FAILURE in 50s (non-voting)

**Pull request merged**
